name: Publish Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build binaries
        run: make cli-build

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/*-linux
            dist/*-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
